### ISSUE TITLE
Determine instructions for the integration of the Aeon request service with PULFALight

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#39]
Please see the existing documentation referenced in https://github.com/projectblacklight/arclight/issues/650#issuecomment-525792114

**Comment by jrgriffiniii** [comment]
There exists a test area in the institutional Aeon installation that we are permitted to use for testing integration. We have been provided with a set of credentials for using a separate, dedicated account for developing integration with the request service (please see the information shared in `Shared-ITIMS-Passwords\aeon` on LastPass)

**Comment by jrgriffiniii** [comment]
Normally the `config/repositories.yml` contains the mapping of form field elements which are used in order to construct the Aeon HTTP request:
```yaml
      request_mappings:
        static:
          Notes: ''
          scheduledDate: ''
          AeonForm: 'EADRequest'
          RequestType: 'Loan'
          GroupingIdentifier: 'ItemVolume'
          GroupingOption_ReferenceNumber: 'Concatenate'
          GroupingOption_ItemNumber: 'Concatenate'
          GroupingOption_ItemDate: 'FirstValue'
          GroupingOption_CallNumber: 'FirstValue'
          GroupingOption_ItemVolume: 'FirstValue'
          GroupingOption_ItemInfo1: 'FirstValue'
          GroupingOption_Location: 'FirstValue'
        accessor:
          DocumentType: document_type
          Site: site
          Location: location
          ItemTitle: title
```

`static` identifies the field values which are constant between Aeon requests, and `accessor` specifies the `SolrDocument` methods which should be invoked in order to retrieve these values on a per-Document basis.

However, from my findings on the PULFA 2.0 application, there are form field names, which themselves, are dynamically generated:

```javascript
{name: "ItemSubTitle_32101037692462", value: "Boyd, Alice: Correspondence, 4 ALsS to Cosmo Monkhouse"},
{name: "ItemTitle_32101037692462", value: "William Bell Scott Collection"},
{name: "ItemDate_32101037692462", value: "1890-1891"},
...
```

Unfortunately, I cannot find a means by which to generate these without overriding [`Arclight::Requests::AeonExternalRequest`](https://github.com/projectblacklight/arclight/blob/master/app/models/arclight/requests/aeon_external_request.rb)
